### ISSUE TITLE
[Suggestion] A class for "tables"

### ISSUE THREAD

**Issue by AndiCui** [pimoroni/displayotron#32]
There are some use cases (like transit time table, etc), where it is useful to devide the display in to columns. (For example: Line Num, Destination, Remianing Mins)
It would be really cool if this can be done with the flexibility to set L/R-Aligned, and a scroll method for longer stuff (In this case destination)

**Comment by AndiCui** [comment]
I did a quick “illustration”, so I can get the point across.
It DOES look great. (At least for me)
![fullsizerender](https://cloud.githubusercontent.com/assets/12994663/18026677/849e679a-6c4f-11e6-88d1-aae626a20f5c.jpg)

PS. Happy long weekend for those are in the UK

**Comment by Gadgetoid** [comment]
That's quite tidy, and potentially useful. It might be worth building as a separate library with an accompanying example, rather than adding too much complexity to the base library though.

Features like auto-scrolling the text would be cool, too.

For UX there's a lot you can do with the 8 custom icons and tidy text placement, too. Plus the character table embedded in the display has boxes, chevrons and other useful tidbits: http://www.lcd-module.de/pdf/doma/dog-m.pdf

**Comment by AndiCui** [comment]
Let's see when I have time to write my dodgy python code. :)
I will paste a link here if I manage to start it.
Cheers

**Comment by AndiCui** [comment]
https://github.com/AndiCui/DOT-Table

**Comment by AndiCui** [comment]
The lib is 80% done.
Still need some clean-up and testing with self defined character.
Consider transfer owner to the official account?

**Comment by Gadgetoid** [comment]
This is good stuff- is there any way we can bring more attention to this in the Display-o-Tron repo?
